/* 
   filename: staticData
   存储静态数据
*/

// districtMp: 上海市行政区到对应景点的映射
var districtMp = [
{text: '黄浦区',
 dot: false,
 children: [{text: '外滩', id: 1},
 {text: "豫园", id: 5},
 {text: "南京路步行街", id: 6},
 {text: "人民广场", id: 9},
 {text: "城隍庙旅游区", id: 11},
 {text: "新天地", id: 12},
 {text: "上海博物馆", id: 13},
 {text: "上海杜莎夫人蜡像馆", id: 15},
 {text: '田子坊', id: 16},
 {text: '外白渡桥', id: 20},
 {text: '黄浦江', id: 31},
 {text: '上海城隍庙', id: 34},
 {text: '淮海路', id: 39},
 {text: '上海城市规划展示馆', id: 62},
 {text: '银行博物馆', id: 63},
 {text: '思南路', id: 66},
 {text: '陈毅广场', id: 68},
 {text: '思南公馆', id: 69},
 {text: '上海老街', id: 77},
 {text: '周公馆', id: 100},
 {text: '中共一大会址', id: 104},
 {text: '老码头', id: 105},
 {text: '上海文庙', id: 106},
 {text: '孙中山故居纪念馆', id: 109},
 {text: '上海外滩美术馆', id: 116},
 {text: '上海当代艺术博物馆', id: 120},
 {text: '外滩万国建筑博览群', id: 123},
 {text: '上海琉璃艺术博物馆', id: 124},
 {text: '上海基督教沐恩堂', id: 126},
 {text: '上海当代艺术馆', id: 140},
 {text: '沉香阁', id: 143},
 {text: '小桃园清真寺',id: 146},
 {text: '上海笔墨博物馆', id: 147},
 {text: '苏州河', id: 41},
 {text: '长乐路', id: 113}]},
{text: '浦东新区',
dot: false,
children: [{text: '东方明珠', id: 2},
 {text: '上海迪士尼度假区', id: 3},
 {text: '上海野生动物园', id: 4},
 {text: '上海科技馆', id: 7},
 {text: '上海海洋水族馆', id: 10},
 {text: '上海环球金融中心', id: 14},
 {text: '世纪公园',id: 17},
 {text: '金茂大厦', id: 18},
 {text: '陆家嘴', id: 26},
 {text: '上海中心大厦上海之巅观光厅', id: 36},
 {text: '中国航海博物馆', id: 44},
 {text: '中华艺术宫', id: 52},
 {text: '陆家嘴中心绿地', id: 54},
 {text: '迪士尼小镇', id: 56},
 {text: '上海中心大厦', id: 67},
 {text: '上海海昌海洋公园', id: 70},
 {text: '金茂大厦88层观光厅', id: 79},
 {text: '滴水湖', id: 81},
 {text: '上海大自然野生昆虫馆', id: 87},
 {text: '外滩观光隧道', id: 88},
 {text: '新场古镇', id: 89},
 {text: '上海世博园', id: 92},
 {text: '上海鲜花港', id: 98},
 {text: '浦东第一图书馆', id: 99},
 {text: '上海环球金融中心观光天阁', id: 115},
 {text: '宝藏湾', id: 117},
 {text: '梅赛德斯-奔驰文化中心', id: 122},
 {text: '浦东开发陈列馆', id: 132},
 {text: '上海滨江森林公园',id: 134},
 {text: '明日世界', id: 137},
 {text: '周浦花海', id: 133}]},
{text: '松江区',
dot: false,
children: [{text: '上海欢乐谷', id: 8},
 {text: '上海影视乐园', id: 24},
 {text: '上海辰山植物园', id: 25},
 {text: '泰晤士小镇', id: 45},
 {text: '上海玛雅海滩水公园', id: 46},
 {text: '佘山国家森林公园', id: 55},
 {text: '月湖雕塑公园', id: 73},
 {text: '方塔园', id: 83},
 {text: '醉白池', id: 108},
 {text: '钟书阁', id: 121},
 {text: '佘山天主教堂', id: 130},
 {text: '天马山公园', id: 145}]},
{text: '长宁区',
dot: false,
children: [{text: '上海动物园', id: 19},
 {text: 'SkyBridgeHQ天会（原凌空SOHO）', id: 114},
 {text: '宋庆龄陵园',id: 149}]},
{text: '青浦区',
dot: false,
children: [{text: '朱家角古镇景区', id: 21},
 {text: '东方绿舟', id: 33},
 {text: '上海大观园', id: 37},
 {text: '放生桥', id: 90},
 {text: '课植园', id: 110},
 {text: '曲水园', id: 127},
 {text: '陈云纪念馆', id: 131},
 {text: '青浦博物馆', id: 148}]},
{text: '静安区',
dot: false,
children: [{text: '上海自然博物馆', id: 22},
 {text: '静安寺', id: 23},
 {text: '马勒别墅', id: 47},
 {text: '上海展览中心', id: 96},
 {text: '上海马戏城', id: 102},
 {text: '静安别墅', id: 118},
 {text: '愚园路', id: 119},
 {text: '毛泽东旧居', id: 135},
 {text: '蔡元培故居', id: 150},
 {text: '大宁郁金香公园', id: 78},
 {text: '巨鹿路', id: 138}]},
{text: '普陀区',
dot: false,
children: [{'text': '上海长风海洋世界', id: 27},
 {text: '长风公园', id: 40},
 {text: '玉佛禅寺', id: 95},
 {text: 'M50创意园', id: 103},
 {text: '真如寺', id: 142}]},
{text: '宝山区',
dot: false,
children: [{text: '顾村公园', id: 28},
 {text: '吴淞炮台湾湿地森林公园', id: 72},
 {text: '上海玻璃博物馆', id: 74}]},
{text: '杨浦区',
dot: false,
children: [{text: '共青国家森林公园', id: 29},
 {text: '复旦大学', id: 59},
 {text: '同济大学', id: 80}]},
{text: '闵行区',
dot: false,
children: [{text: '锦江乐园', id: 30},
 {text: '七宝老街', id: 50},
 {text: '召稼楼', id: 57}]},
{text: '虹口区',
dot: false,
children: [{text: '1933老场坊', id: 42},
 {text: '鲁迅公园', id: 58},
 {text: '甜爱路', id: 75},
 {text: '多伦路文化名人街', id: 84},
 {text: '上海邮政博物馆', id: 94},
 {text: '上海犹太难民纪念馆', id: 111},
 {text: '鲁迅故居', id: 139},
 {text: '鲁迅纪念馆', id: 141}]},
{text: '徐汇区',
 dot: false,
children: [{text: '武康路', id: 43},
 {text: '宋庆龄故居纪念馆', id: 60},
 {text: '武康大楼', id: 64},
 {text: '上海交通大学', id: 65},
 {text: '上海电影博物馆', id: 71},
 {text: '徐家汇天主教堂', id: 76},
 {text: '龙华寺', id: 101},
 {text: '巴金故居', id: 107},
 {text: '徐家汇源景区', id: 112},
 {text: '上海工艺美术博物馆', id: 125},
 {text: '丁香花园', id: 129},
 {text: '龙美术馆西岸馆', id: 136},
 {text: '上海话剧艺术中心', id: 144},
 {text: '上海植物园',id: 35}]},
{text: '奉贤区',
dot: false,
children: [{text: '上海海湾国家森林公园', id: 48}, {'text': '碧海金沙', id: 97}]},
{text: '金山区',
dot: false,
children: [{text: '枫泾古镇', id: 49},
 {text: '金山城市沙滩', id: 61},
 {text: '东林寺', id: 86}]},
{text: '嘉定区',
dot: false,
children: [{text: '上海汽车博物馆', id: 51},
 {text: '南翔古镇', id: 53},
 {text: '秋霞圃', id: 91},
 {text: '嘉定孔庙', id: 128},
 {text: '古猗园', id: 32}]},
{text: '崇明区',
dot: false,
children: [{text: '东平国家森林公园', id: 38},
 {text: '崇明岛国家地质公园', id: 82},
 {text: '西沙湿地公园', id: 85},
 {text: '东滩湿地公园', id: 93},]},
]

// season2Attr: 季节到景点的映射
var season2Attr={

}
module.exports = {
  districtMp,
  season2Attr
};